#!/usr/bin/env python

import sys
import claripy
import angr
from angrutils import *
import networkx as nx

import csv

def write_functions_csv(filename, functions):
	fields = ["func_name", "func_addr"]
	with open(filename, mode='w', newline='') as file:
		writer = csv.DictWriter(file, fieldnames=fields)
		writer.writeheader()
		for func in functions:
			writer.writerow(func)
