#!/usr/bin/env python

import sys
import claripy
import angr
from angrutils import *

if len(sys.argv) < 2:
    print("Usage: script.py <path_to_elf_file>")
    sys.exit(1)

elf_file = sys.argv[1]

project = angr.Project(elf_file, load_options={'auto_load_libs': False})

cfg = project.analyses.CFGEmulated(keep_state=True)
print("This is the graph:", cfg.graph)
print("It has %d nodes and %d edges" % (len(cfg.graph.nodes()), len(cfg.graph.edges())))


print("List of functions in the binary:")
for func_addr, func in cfg.kb.functions.items():
    print(f"Function name: {func.name}, Address: {hex(func_addr)}")