#!/usr/bin/env python

import sys
import claripy
import angr
from angrutils import *
import networkx as nx

import dill
import pickle
import yaml

import csv





if len(sys.argv) < 2:
    print("Usage: script.py <path_to_res>" )
    sys.exit(1)


elf_file = sys.argv[1]
res_folder = sys.argv[2]

project = angr.Project(elf_file, load_options={'auto_load_libs': False})

# load graph object from file
with open(res_folder + "/elf.dill", 'rb') as f:
    project, cfg = dill.load(f)

cfg.project = project

print("This is the graph:", cfg.graph)
print("It has %d nodes and %d edges" % (len(cfg.graph.nodes()), len(cfg.graph.edges())))



print("List of functions in the binary:")
for func_addr, func in cfg.kb.functions.items():
    print(f"Function name: {func.name}, Address: {hex(func_addr)}")